"""
ADOBMD Exporter - Export to various molecular file formats

This file is part of Quantum Analysis Helper.
Quantum Analysis Helper is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Copyright (C) [2026] Acxel David Orozco Baldomero
"""

import os
import sys
import numpy as np
from pathlib import Path
from typing import Optional
import subprocess
import tempfile

try:
    from ase import Atoms
    ASE_AVAILABLE = True
except ImportError:
    ASE_AVAILABLE = False

class ADOBMDExporter:
    """Export ADOBMD data to various molecular formats"""
    
    def __init__(self, data):
        """
        Initialize exporter with ADOBMD data
        
        Args:
            data: ADOBMDData object containing the molecular system
        """
        self.data = data
    
    def to_xyz(self, filename: str, with_qm_marker: bool = False):
        """
        Export to XYZ format (standard for most viewers)
        
        Args:
            filename: Output file path
            with_qm_marker: Add QM/MM markers in comment line
        """
        with open(filename, 'w') as f:
            f.write(f"{len(self.data.atoms)}\n")
            
            if with_qm_marker:
                qm_count = len([a for a in self.data.atoms if a.is_qm])
                f.write(f"ADOBMD export - {self.data.filename} - QM atoms: {qm_count}\n")
            else:
                f.write(f"ADOBMD export - {self.data.filename}\n")
            
            for atom in self.data.atoms:
                f.write(f"{atom.element:<2} {atom.x:15.8f} {atom.y:15.8f} {atom.z:15.8f}\n")
        
        print(f"[ADOBMD] Exported XYZ to: {filename}")
        return filename
    
    def to_sdf(self, filename: str):
        """
        Export to SDF format (Structure Data File)
        
        Args:
            filename: Output file path
        """
        with open(filename, 'w') as f:
            # Header
            f.write(f"{self.data.filename}\n")
            f.write("  ADOBMD Export\n")
            f.write("\n")
            
            # Counts line
            n_atoms = len(self.data.atoms)
            n_bonds = len(self.data.bonds)
            f.write(f"{n_atoms:3d}{n_bonds:3d}  0  0  0  0  0  0  0  0  1 V2000\n")
            
            # Atoms block
            for atom in self.data.atoms:
                f.write(f"{atom.x:10.4f}{atom.y:10.4f}{atom.z:10.4f} {atom.element:<2s} 0  0  0  0  0  0  0  0  0  0  0  0\n")
            
            # Bonds block
            for bond in self.data.bonds:
                f.write(f"{bond.atom1:3d}{bond.atom2:3d}{bond.order:3d}  0  0  0  0\n")
            
            # End marker
            f.write("M  END\n")
        
        print(f"[ADOBMD] Exported SDF to: {filename}")
        return filename
    
    def to_pdb(self, filename: str):
        """
        Export to PDB format (Protein Data Bank)
        
        Args:
            filename: Output file path
        """
        from datetime import datetime
        
        with open(filename, 'w') as f:
            # Header
            f.write(f"HEADER    ADOBMD EXPORT                {datetime.now().strftime('%d-%b-%y').upper()}\n")
            f.write(f"TITLE     {self.data.filename[:60]}\n")
            f.write(f"REMARK    Generated by ADOBMD Visualizer\n")
            f.write(f"REMARK    Atoms: {len(self.data.atoms)}  Bonds: {len(self.data.bonds)}\n")
            
            if self.data.has_qm_region:
                qm_count = len([a for a in self.data.atoms if a.is_qm])
                f.write(f"REMARK    QM region: {qm_count} atoms\n")
            
            # Atoms
            for i, atom in enumerate(self.data.atoms, 1):
                # PDB format: fixed columns
                record = "ATOM"
                serial = i
                name = f"{atom.element:<3}"
                alt_loc = ""
                res_name = "MOL"
                chain_id = "A"
                res_seq = atom.molecule
                i_code = ""
                x, y, z = atom.x, atom.y, atom.z
                occupancy = 1.00
                temp_factor = 0.00
                element = atom.element.rjust(2)
                charge = ""
                
                line = (f"{record:<6}{serial:>5} {name:>4}{alt_loc:1}{res_name:<3} "
                       f"{chain_id:1}{res_seq:>4}{i_code:1}   "
                       f"{x:>8.3f}{y:>8.3f}{z:>8.3f}{occupancy:>6.2f}{temp_factor:>6.2f}          "
                       f"{element:>2}{charge:>2}\n")
                f.write(line)
            
            # Bonds (CONECT records)
            if self.data.bonds:
                # Group bonds by first atom for CONECT records
                bond_dict = {}
                for bond in self.data.bonds:
                    if bond.atom1 not in bond_dict:
                        bond_dict[bond.atom1] = []
                    bond_dict[bond.atom1].append(bond.atom2)
                    
                    if bond.atom2 not in bond_dict:
                        bond_dict[bond.atom2] = []
                    bond_dict[bond.atom2].append(bond.atom1)
                
                for atom_id, bonded in bond_dict.items():
                    if bonded:
                        bonded = sorted(set(bonded))[:4]  # PDB allows max 4 bonds per CONECT
                        line = f"CONECT{atom_id:5d}"
                        for b in bonded:
                            line += f"{b:5d}"
                        f.write(line + "\n")
            
            f.write("END\n")
        
        print(f"[ADOBMD] Exported PDB to: {filename}")
        return filename
    
    def to_cif(self, filename: str):
        """
        Export to CIF format (Crystallographic Information File)
        
        Args:
            filename: Output file path
        """
        with open(filename, 'w') as f:
            f.write(f"data_{Path(self.data.filename).stem}\n")
            f.write("#\n")
            f.write(f"_audit_creation_method  'ADOBMD Visualizer'\n")
            f.write(f"_chemical_name_common    '{self.data.title}'\n" if self.data.title else "")
            f.write("#\n")
            
            # Cell parameters if box is available
            if self.data.has_box:
                a = self.data.box_hi[0] - self.data.box_lo[0]
                b = self.data.box_hi[1] - self.data.box_lo[1]
                c = self.data.box_hi[2] - self.data.box_lo[2]
                f.write(f"_cell_length_a    {a:.4f}\n")
                f.write(f"_cell_length_b    {b:.4f}\n")
                f.write(f"_cell_length_c    {c:.4f}\n")
                f.write("_cell_angle_alpha 90.0000\n")
                f.write("_cell_angle_beta  90.0000\n")
                f.write("_cell_angle_gamma 90.0000\n")
                f.write("#\n")
            
            # Atoms
            f.write("loop_\n")
            f.write("_atom_site_label\n")
            f.write("_atom_site_type_symbol\n")
            f.write("_atom_site_fract_x\n")
            f.write("_atom_site_fract_y\n")
            f.write("_atom_site_fract_z\n")
            f.write("_atom_site_charge\n")
            
            for i, atom in enumerate(self.data.atoms, 1):
                label = f"{atom.element}{i}"
                f.write(f"{label:<6} {atom.element:<2} {atom.x:10.6f} {atom.y:10.6f} {atom.z:10.6f} {atom.charge:6.3f}\n")
        
        print(f"[ADOBMD] Exported CIF to: {filename}")
        return filename
    
    def to_gro(self, filename: str):
        """
        Export to GROMACS GRO format
        
        Args:
            filename: Output file path
        """
        with open(filename, 'w') as f:
            # Title
            f.write(f"ADOBMD Export: {self.data.filename}\n")
            
            # Number of atoms
            f.write(f"{len(self.data.atoms):5d}\n")
            
            # Atoms
            for i, atom in enumerate(self.data.atoms, 1):
                # GRO format: fixed width
                res_nr = atom.molecule
                res_name = "MOL"
                atom_name = atom.element
                atom_nr = i
                x, y, z = atom.x / 10.0, atom.y / 10.0, atom.z / 10.0  # Convert to nm
                
                f.write(f"{res_nr:5d}{res_name:<5}{atom_name:>5}{atom_nr:5d}{x:8.3f}{y:8.3f}{z:8.3f}\n")
            
            # Box
            if self.data.has_box:
                a = (self.data.box_hi[0] - self.data.box_lo[0]) / 10.0  # Convert to nm
                b = (self.data.box_hi[1] - self.data.box_lo[1]) / 10.0
                c = (self.data.box_hi[2] - self.data.box_lo[2]) / 10.0
                f.write(f"{a:10.5f}{b:10.5f}{c:10.5f}\n")
            else:
                # Default box
                coords = np.array([[a.x, a.y, a.z] for a in self.data.atoms])
                max_coord = np.max(coords, axis=0) / 10.0
                min_coord = np.min(coords, axis=0) / 10.0
                box = max_coord - min_coord + 2.0
                f.write(f"{box[0]:10.5f}{box[1]:10.5f}{box[2]:10.5f}\n")
        
        print(f"[ADOBMD] Exported GRO to: {filename}")
        return filename
    
    def to_mol2(self, filename: str):
        """
        Export to Tripos MOL2 format
        
        Args:
            filename: Output file path
        """
        with open(filename, 'w') as f:
            # Header
            f.write("@<TRIPOS>MOLECULE\n")
            f.write(f"{Path(self.data.filename).stem}\n")
            f.write(f"{len(self.data.atoms):5d} {len(self.data.bonds):5d} 0 0 0\n")
            f.write("SMALL\n")
            f.write("NO_CHARGES\n")
            f.write("\n")
            
            # Atoms
            f.write("@<TRIPOS>ATOM\n")
            for i, atom in enumerate(self.data.atoms, 1):
                # MOL2 format: atom_id atom_name x y z atom_type subst_id subst_name charge
                atom_type = atom.element
                if atom.element == 'C':
                    atom_type = 'C.3'  # sp3 carbon
                elif atom.element == 'N':
                    atom_type = 'N.3'  # sp3 nitrogen
                elif atom.element == 'O':
                    atom_type = 'O.3'  # sp3 oxygen
                elif atom.element == 'H':
                    atom_type = 'H'
                
                f.write(f"{i:6d} {atom.element:<4} {atom.x:10.4f} {atom.y:10.4f} {atom.z:10.4f} "
                       f"{atom_type:<5} 1 MOL {atom.charge:8.4f}\n")
            
            # Bonds
            if self.data.bonds:
                f.write("@<TRIPOS>BOND\n")
                for i, bond in enumerate(self.data.bonds, 1):
                    bond_type = '1'  # single bond
                    if bond.order == 2:
                        bond_type = '2'
                    elif bond.order == 3:
                        bond_type = '3'
                    elif bond.order == 4:
                        bond_type = 'ar'
                    
                    f.write(f"{i:6d} {bond.atom1:5d} {bond.atom2:5d} {bond_type:>2}\n")
        
        print(f"[ADOBMD] Exported MOL2 to: {filename}")
        return filename
    
    def to_xyz_with_bonds(self, filename: str):
        """
        Export to extended XYZ format with bond information
        
        Args:
            filename: Output file path
        """
        with open(filename, 'w') as f:
            f.write(f"{len(self.data.atoms)}\n")
            f.write(f"Lattice=\"{self.data.box_lo[0]} 0 0 0 {self.data.box_lo[1]} 0 0 0 {self.data.box_lo[2]}\" "
                   f"Properties=species:S:1:pos:R:3:charge:R:1:qm_flag:L:1 pbc=\"T T T\"\n")
            
            for atom in self.data.atoms:
                qm_flag = 1 if atom.is_qm else 0
                f.write(f"{atom.element:<2} {atom.x:15.8f} {atom.y:15.8f} {atom.z:15.8f} "
                       f"{atom.charge:8.4f} {qm_flag:1d}\n")
            
            # Add bond information as comment
            if self.data.bonds:
                f.write("# Bonds:\n")
                for bond in self.data.bonds:
                    f.write(f"# {bond.atom1} {bond.atom2} {bond.order}\n")
        
        print(f"[ADOBMD] Exported extended XYZ to: {filename}")
        return filename
    
    def to_ase_atoms(self):
        """
        Convert to ASE Atoms object for further processing
        
        Returns:
            ASE Atoms object or None if ASE not available
        """
        if not ASE_AVAILABLE:
            print("[ADOBMD] ASE not installed. Install with: pip install ase")
            return None
        
        symbols = [atom.element for atom in self.data.atoms]
        positions = [[atom.x, atom.y, atom.z] for atom in self.data.atoms]
        
        # Create ASE Atoms object
        atoms = Atoms(symbols=symbols, positions=positions)
        
        # Add cell if box available
        if self.data.has_box:
            cell = [
                [self.data.box_hi[0] - self.data.box_lo[0], 0, 0],
                [0, self.data.box_hi[1] - self.data.box_lo[1], 0],
                [0, 0, self.data.box_hi[2] - self.data.box_lo[2]]
            ]
            atoms.set_cell(cell)
            atoms.set_pbc(True)
        
        return atoms
    
    def launch_viewer(self, viewer: str = 'vmd'):
        """
        Launch external viewer with current structure
        
        Args:
            viewer: 'vmd', 'pymol', 'avogadro', or 'jmol'
        """
        # Create temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.xyz', delete=False) as tmp:
            self.to_xyz(tmp.name)
            temp_file = tmp.name
        
        viewer_cmds = {
            'vmd': ['vmd', temp_file],
            'pymol': ['pymol', temp_file],
            'avogadro': ['avogadro', temp_file],
            'jmol': ['jmol', temp_file],
            'chimera': ['chimera', temp_file],
            'vesta': ['vesta', temp_file]
        }
        
        if viewer not in viewer_cmds:
            print(f"[ADOBMD] Unknown viewer: {viewer}")
            return
        
        try:
            print(f"[ADOBMD] Launching {viewer}...")
            subprocess.Popen(viewer_cmds[viewer])
        except FileNotFoundError:
            print(f"[ADOBMD] {viewer} not found. Please install it first.")
            # Try to open with default application
            try:
                if os.name == 'nt':  # Windows
                    os.startfile(temp_file)
                elif os.name == 'posix':  # macOS and Linux
                    subprocess.run(['open', temp_file] if sys.platform == 'darwin' else ['xdg-open', temp_file])
            except:
                print(f"[ADOBMD] Could not open file. It's saved at: {temp_file}")
    
    def get_export_formats(self):
        """Get list of available export formats"""
        return {
            'XYZ': '.xyz',
            'SDF': '.sdf',
            'PDB': '.pdb',
            'CIF': '.cif',
            'GRO': '.gro',
            'MOL2': '.mol2',
            'Extended XYZ': '.xyz'
        }